# Generated by Django 3.2.9 on 2021-12-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20211203_1006'),
        ('users', '0003_auto_20211203_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='Opublikowano')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
