# Generated by Django 3.2.9 on 2021-12-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211203_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
