# Generated by Django 3.2.9 on 2021-11-10 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategories',
            options={'verbose_name': 'Kategory', 'verbose_name_plural': 'Kategories'},
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='count',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 10, 21, 43, 45, 150934)),
        ),
    ]
