# Generated by Django 3.2.9 on 2021-11-13 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211110_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 13, 15, 29, 42, 424586)),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
