# Generated by Django 3.2.9 on 2021-11-30 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211113_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='username',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.user'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 30, 18, 31, 45, 702283)),
        ),
    ]
