# Generated by Django 3.2.9 on 2021-12-01 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipes_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Kategories',
        ),
        migrations.AlterModelOptions(
            name='kategories',
            options={'verbose_name': 'Kategory', 'verbose_name_plural': 'Kategories'},
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='category',
            new_name='kategory',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 21, 19, 22, 896028)),
        ),
    ]
