# Generated by Django 3.2.9 on 2021-12-01 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipes_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategories',
            new_name='Categories',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='kategory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 21, 31, 15, 369226)),
        ),
    ]
