# Generated by Django 3.2.9 on 2021-12-03 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211203_0950'),
        ('recipes', '0018_auto_20211203_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 9, 50, 26, 141190)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
