# Generated by Django 3.2.9 on 2021-12-03 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_recipes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 10, 17, 54, 303596)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.user'),
        ),
    ]
