# Generated by Django 3.2.9 on 2021-12-03 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20211203_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 10, 29, 57, 135545)),
        ),
    ]
