# Generated by Django 3.2.9 on 2021-12-03 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_alter_recipes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='author',
        ),
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ManyToManyField(to='recipes.User'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 11, 51, 17, 198292)),
        ),
    ]
